CC = cc
CFLAGS = -Wall -Wextra -Werror
SRC = backtrack.c check_table.c free_memory.c main.c no_repeat.c solve.c print_table.c make_empty_table.c check_rows.c check_columns.c
all:
	$(CC) $(CFLAGS) $(SRC) -o a.out
clean:
	rm -f a.out
fclean:
	rm 
re:
	